language: android
dist: trusty
android:
  components:
    - build-tools-28.0.3
    - android-28
    - add-on
    - extra
    - ndk
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'android-ndk-license-.+'

script: sdkmanager --list

